name: power_meter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  fonts:
    - family: e-Ukraine
      fonts:
        - asset: assets/fonts/e-UkraineHead-Regular.otf
        - asset: assets/fonts/e-UkraineHead-Medium.otf
          weight: 500
        - asset: assets/fonts/e-UkraineHead-Bold.otf
          weight: 700
        - asset: assets/fonts/e-UkraineHead-Light.otf
          weight: 300
        - asset: assets/fonts/e-UkraineHead-Thin.otf
          weight: 100